version: '2'
services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    command: mongod --smallfiles
    volumes:
     - /Users/daniel/Documents/Development/java/docker-map:/data/db
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
  configuration-service:
    image: drm3107/configuration-service
    container_name: configuration-service
    ports:
     - "8888:8888"
  service-registry:
    image: drm3107/service-registry
    container_name: service-registry
    ports:
     - "8761:8761"
  order-service:
    image: drm3107/order-service
    container_name: order-service
    depends_on:
     - mongodb
     - rabbitmq
     - service-registry
     - configuration-service
    ports:
      - "8900:8900"
